# Generated by Django 5.0.4 on 2024-06-15 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Django', 'Django'), ('Android', 'Android'), ('PHP', 'PHP'), ('Spring', 'Spring'), ('Nodejs', 'Nodejs')], max_length=50)),
                ('screenshots', models.ImageField(upload_to='projects/media/uploads/')),
                ('technologies', models.CharField(max_length=100)),
                ('live_site_link', models.URLField(blank=True, null=True)),
                ('RatePeopleNo', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('lastRating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
